[package]
name = "Syracuse"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow          =   {version = "1.0.*"}
clap            =   {version = "4.5.*", features = ["cargo"]}
crossterm       =   {version = "0.27.*"}
serde           =   {version = "1.0.*", features = ["derive"]}
serde_json      =   {version = "1.0.*"}
serde_with      =   {version = "3.6.*"}
time            =   {version = "0.3.*", features = ["serde"]}
