[package]
name = "Syracuse"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow          =   {version = "1.0.*"}
clap            =   {version = "4.5.*", features = ["cargo"]}
crossterm       =   {version = "0.27.*", features = ["serde"]}
rand            =   {version = "0.8.*"}
itertools       =   {version = "0.12.*"}
plotters        =   {version = "0.3.*"}
serde           =   {version = "1.0.*", features = ["derive"]}
serde_json      =   {version = "1.0.*"}
serde_with      =   {version = "3.6.*"}
time            =   {version = "0.3.*", features = ["serde"]}
