[package]
name = "syracuse"
version = "1.2.0"
edition = "2021"

[dependencies]
anyhow          =   {version = "1.0.*"}
clap            =   {version = "4.5.*", features = ["cargo"]}
crossterm       =   {version = "0.27.*", features = ["serde"]}
itertools       =   {version = "0.12.*"}
plotters        =   {version = "0.3.*"}
serde           =   {version = "1.0.*", features = ["derive"]}
serde_json      =   {version = "1.0.*"}
time            =   {version = "0.3.*", features = ["serde"]}

[profile.release]
opt-level = 3
lto = true
panic = "abort"
strip = "symbols"
codegen-units = 1