[package]
name = "Syracuse"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow          =   {version = "1.0.*"}
bincode         =   {version = "1.3.*"}
clap            =   {version = "4.5.*", features = ["cargo"]}
crossterm       =   {version = "0.27.*"}
serde           =   {version = "1.0.*", features = ["derive"]}
time            =   {version = "0.3.*", features = ["serde"]}
